### ISSUE TITLE
Indigo moveit_robots Package Release

### ISSUE THREAD

**Issue by rethink-imcmahon** [ros-planning/moveit_robots#31]
I've noticed that there are several `*_moveit_config` packages being built on the ROS buildfarm, but none of the packages from `moveit_robots` are present:
http://www.ros.org/debbuild/indigo.html?q=_moveit_config

I realize `moveit_robots` is a rather atypical set of packages, mostly consisting of launchfiles. That said, are there any plans to bloom this repo and push it up to the buildfarm?

**Comment by 130s** [comment]
+1.
I've been also wondering why the packages here aren't released.

**Comment by sachinchitta** [comment]
Although the original intent of this repo was a home for MoveIt! packages for different robots, its not ideal. Most people have one robot that they want the packages for and they might be forced to download packages for every robot out there. I would suggest thinking about breaking this up and then releasing things individually for each robot, e.g. moveit_baxter, etc.

**Comment by rethink-imcmahon** [comment]
Interesting idea, @sachinchitta. I am definitely open to hosting an independent repo for `moveit_baxter`. There would be a few logistical challenges such as migrating users off this repo, but the benefits of then being able to maintain multiple ROS version specific branches would likely outweigh the challenges.

However, if we were to bloom this repo as is, all of the packages would be individually installable without requiring the other robot's `moveit_robots` packages. If I'm not mistaken, to install all the packages in this repo at once would require a meta-package named `moveit_robots` that depended on every other `moveit_robots` package in its `package.xml`.

**Comment by 130s** [comment]
> However, if we were to bloom this repo as is, all of the packages would
be individually installable without requiring the other robot's
moveit_robots packages. If I'm not mistaken, to install all the packages in
this repo at once would require a meta-package named moveit_robots that
depended on every other moveit_robots package in its package.xml.

That's correct to my knowledge.

Since my team uses multiple robots some of their MoveIt! packages reside
here, the repository like this is very convenient. However, I also
understand that that might not be the case for the majority of the users.

Users could be forced to obtain unnecessary resources if they download
sources, unless they use mantras like git sparse checkout. Users can
benefit from installing by DEB, since they can pick only what they want.

That said I'm still +1 for the release.

**Comment by 130s** [comment]
How do you think @sachinchitta ?

It would be great for many users if moveit config packages provided here are available as binary. So either we release from this `moveit_robots` repo or from other repos separately for each robot, I appreciate if we can move this forward.

**Comment by sachinchitta** [comment]
@130s you have merge access.

**Comment by 130s** [comment]
Done in https://github.com/ros/rosdistro/pull/9503.
